export { default as Home } from "./Home/Home";
export { default as Test } from "./Test/Test";
export { default as AuthLayout } from "./Auth/AuthLayout";
export { default as PlanCreate } from "./Plan/CreatePlan/CreatePlan";
export {default as PlanList} from "./Plan/List/PlanList";
export { default as PreferenceLayout } from "./Preference/PreferenceLayout";
export { default as SearchLayout } from "./Search/SearchLayout";
export { default as Notice } from "./Notice/Notice";
export { default as Board } from "./Board/Board";
export { default as BoardDetail } from "./Board/Detail/BoardDetail";
export { default as BoardWrite } from "./Board/Write/BoardWrite";
export {default as MyPage} from "./MyPage/MyPage";
export {default as Destination} from "./Destination/Destination";
